name = "PGLib"
uuid = "07a8691f-3d11-4330-951b-3c50f98338be"
authors = ["Noah Rhodes <nrhodes@wisc.edu>"]
version = "0.1.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"

[compat]
PowerModels = "~0.18, ~0.19"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
